name: GitHub CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build application
      run: cargo build --verbose
    - name: Run tests
      run: cargo test
